build(phase2): translated to typescript
vlad-karnauch/wix-onboarding pull request #3
Opened 2021-03-17 13:43 UTC by Vladkarna

Also used `create-stylable-app`

2021-03-17 15:10 UTC, eifr0980 requested changes
few things:
* a clearer description would be helpful
* move all imgs to an `assets` folder
* there are changes in this PR that are not related to the title (eslint, gitignore, extension recommendations, etc.)

2021-03-17 15:10 UTC, eifr0980 commented on Test
> +
?

2021-03-17 15:10 UTC, eifr0980 commented on src/app.st.css
> +    color: white; */
comments?

2021-03-17 15:10 UTC, eifr0980 commented on src/app.st.css
> +}
add new line

2021-03-17 15:10 UTC, eifr0980 commented on src/dropdown/dropdown.tsx
> +}
new line

2021-03-17 15:10 UTC, eifr0980 commented on src/dropdown/dropdownProps.tsx
> +}
new line

2021-03-17 15:10 UTC, eifr0980 commented on src/index.tsx
> +// dropDown.unmount();
new line
comment

2021-03-17 16:30 UTC, PeterShershov requested changes
@eladdo92 and I went over your PR together. Good job! see some comments above.

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +        const eventListener: (()=> void)|null = enabled ? () =>  {this.handleTriggerItemClick()} : null;
you can also formatOnSave in vs code settings

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +    private handleTriggerItemClick() {
add return type

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +        return !optionItemsContainer.classList.contains('hidden-option-items-container');
extract `hidden-option-items-container` to a const

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +        return this.rootNode.getElementsByClassName(Dropdown.optionItemsClass)[0];
you can just use `querySelector` and get the first one by default

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +        const optionItemsContainer: Element = this.getOptionItemsContainer();
Type `Element` is inferred so no need to declare it.

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +    private makeItemNodeWithText(text: string, className: string|null, onClickListener: (()=>void)|null) {
`className` will always be a string right? if it's optional, you can make it `undefined` by adding a `?` after the argument name like: `className?: string`.

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +    private makeItemNodeWithText(text: string, className: string|null, onClickListener: (()=>void)|null) {
I would rename `onClickListener` to `onClick` and make it optional using `undefined` and not `null`

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +        const textNode: Text = this.makeTextNode(text);
these types are inferred by the return type of the methods. Add return types to all of them.

2021-03-17 16:30 UTC, PeterShershov commented on webpack.config.js
> +                //   ],
woops

2021-03-17 16:30 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +    private makeItemNode(className: string|null, onClickListener: (() => void)|null) {
when you have multiple optional params, use one object param with optional keys:
`makeItemNode(options: { className?: string, onClickListener?: () => void })`

2021-03-18 07:21 UTC, Vladkarna commented on src/dropdown/dropdown.tsx
> +        const eventListener: (()=> void)|null = enabled ? () =>  {this.handleTriggerItemClick()} : null;
yeah its about time to add prettier

2021-03-18 08:30 UTC, Vladkarna commented on src/dropdown/dropdown.tsx
> +    private makeItemNode(className: string|null, onClickListener: (() => void)|null) {
nice

2021-03-18 13:58 UTC, Vladkarna commented on .gitignore
>  .DS_Store
For this

https://vladkarna.github.io/wix-onboarding/dist/

2021-03-18 21:10 UTC, eifr0980 requested changes

2021-03-18 21:10 UTC, eifr0980 commented on src/stylable.svg
> +<?xml version="1.0" encoding="UTF-8"?>
take a look at the comment from previous CR 
https://github.com/Vladkarna/wix-onboarding/pull/3#pullrequestreview-614414113

2021-03-18 21:10 UTC, eifr0980 commented on src/header.tsx
> +                <img className={classes.icon} src={stylableLogo} width={50} height={50} alt="" />
why use attributes instead of styling ?

2021-03-18 21:10 UTC, eifr0980 commented on src/dropdown/dropdownOption.tsx
> +}
why `dropdownProps` in it's own file and this is here?

2021-03-21 07:38 UTC, Vladkarna commented on tsconfig.json
> +    "jsx": "react",                           /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
Yeah, just read about it yesterday, looks nice!

2021-03-21 07:40 UTC, Vladkarna commented on src/stylable.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Yeah, notice I moved arrow.png.
The thing is i built the project using create-stylable-app package, so I didn't change anything from the 'original project'

2021-03-21 07:42 UTC, Vladkarna commented on src/header.tsx
> +                <img className={classes.icon} src={stylableLogo} width={50} height={50} alt="" />
Dunno, I used create-stylable-app, that's their code, i'll clean it up when I get to react in the onboarding (next phase).

2021-03-21 07:45 UTC, Vladkarna commented on src/dropdown/dropdownOption.tsx
> +}
Ahhm, that's DropdownOption, its enum, and util function related to it?
What would be the first place you'd look for the util functions?

2021-03-21 07:50 UTC, Vladkarna commented on README.md
> +  An easy to use, editable, and reusable, dropdown. See the result: http://vladkarna.github.io/wix-onboarding/dist
Yeah, the thing is, github allows to either access the url via root or via docs folder.
Put it in docs for now, but that's just until the merge with master, once that happens i'll remove the files and they will be built automatically with every new push to master.

2021-03-21 10:05 UTC, eifr0980 commented on app/dropdown/dropdown.css
> +    width: 12em;
Why changed to `em` from var?

2021-03-21 10:14 UTC, eifr0980 commented on src/index.tsx
> +import { Dropdown, Props } from './dropdown/dropdown';
fix `Props` import to correct place and name

2021-03-21 10:15 UTC, PeterShershov requested changes
Reviewed with @eladdo92

2021-03-21 10:15 UTC, PeterShershov commented on src/dropdown/dropdown.tsx
> +        return this.makeItemNode({ class: className, onClick: eventHandler, text: text });
Same comment as before, although you can just move the entire logic of enabled / disabled into `makeItemNode` and get it in the options object from arguments.

2021-03-21 10:15 UTC, PeterShershov commented on src/dropdown/dropdownProps.tsx
> +export interface DropdownProps {
Change file to `.ts`

2021-03-21 10:19 UTC, eifr0980 commented on src/dropdown/dropdown.tsx
> +        const dropDown = this.makeNode('ul', 'dropdown');
dropdown*

2021-03-21 10:31 UTC, eifr0980 commented on src/dropdown/dropdown.tsx
> +        class?: string;
IMO `className` will be clearer, especially when in all other places in the same file it's called `className`

@PeterShershov what do you think?

2021-03-21 10:48 UTC, eifr0980 commented on src/dropdown/dropdown.tsx
> +    constructor(parent: Element, options: DropdownOption[], props: DropdownProps) {
add JSDocs

2021-03-21 10:50 UTC, eifr0980 commented on src/dropdown/dropdown.tsx
> +
`type` import should be last

2021-03-21 10:53 UTC, eifr0980 commented on src/index.tsx
> +const dropDown = new Dropdown(root, longOptions, props); //appends to root
`dropdown`

2021-03-21 11:04 UTC, Vladkarna commented on app/dropdown/dropdown.css
> +    width: 12em;
woops

2021-03-21 11:12 UTC, Vladkarna commented on src/index.tsx
> +import { Dropdown, Props } from './dropdown/dropdown';
I feel so dumb right now

2021-03-21 11:13 UTC, Vladkarna commented on app/dropdown/dropdown.js
> +        this.#closeOnOutsideClick();
yeah, @eifr0980 said the same.

2021-03-21 11:18 UTC, Vladkarna commented on src/dropdown/dropdown.classic.css
> +  box-sizing: content-box;
Update: if I remove content-box the trigger item (selector) will become smaller

2021-03-21 11:23 UTC, Vladkarna commented on src/dropdown/dropdown.classic.css
> +  border: 1px solid var(--background-color); /* to clear spacing between lines */
with margin, you can see the text that's behind
![Screen Shot 2021-03-21 at 13 22 11](https://user-images.githubusercontent.com/75258238/111902963-88109a80-8a48-11eb-9506-02f644d7d04f.png)

2021-03-21 11:27 UTC, Vladkarna commented on src/dropdown/dropdown.tsx
> +    private makeTriggerToggleNode(enabled: boolean): Element {
This is actually the item you click, @eifr0980 didn't understand it either. I'll change it to 'Selected...'

2021-03-21 11:36 UTC, Vladkarna commented on src/dropdown/dropdown.tsx
> +            const textNode = this.makeTextNode(params.text);
Ahhh, I wanted to separate all calls to document. into their own functions so that they can be changed

2021-03-21 15:28 UTC, eladdo92 requested changes

2021-03-21 15:28 UTC, eladdo92 commented on src/dropdown/dropdown.classic.css
> +  border: 1px solid var(--background-color); /* to clear spacing between lines */
give bgColr to .option-items-container

2021-03-21 15:28 UTC, eladdo92 commented on src/dropdown/dropdownOption.ts
> +    disabled?: boolean;
why did you remove the `type`?

2021-03-21 15:28 UTC, eladdo92 commented on src/dropdown/dropdownOption.ts
> +export function dividerOption(): DropdownOption {
add another type for the divider

2021-03-21 15:28 UTC, eladdo92 commented on src/dropdown/dropdown.ts
> +    private isTextOption(option: DropdownOption | TextOption): option is TextOption {
should be exposed as a util from `dropdownOption.ts` like the options creators

2021-03-21 15:28 UTC, eladdo92 commented on src/dropdown/dropdown.ts
> +    private makeOptionItems(options: (DropdownOption | TextOption)[], enabled: boolean): Element {
1. `TextOption` extends `DropdownOption` so you could just wrote `DropdownOption`
2. `DropdownOption | TextOption` is not clear, if we have the type `TextOption`, what is the type `DropdownOption`?

2021-03-22 09:27 UTC, eladdo92 requested changes

2021-03-22 09:27 UTC, eladdo92 commented on test/dropdown-driver.ts
> +import { Simulate } from 'react-dom/test-utils';
not related to this PR

2021-03-22 09:27 UTC, eladdo92 commented on test/dropdown.spec.tsx
> +import React from 'react';
not related to this PR

2021-03-22 09:27 UTC, eladdo92 commented on test-kit/render.ts
> +import ReactDOM from 'react-dom';
not related to this PR

2021-03-22 09:27 UTC, eladdo92 commented on src/dropdown/dropdownOption.ts
> +export function dividerOption(): DropdownOption {
`export function dividerOption(): DividerDropdownOption`

2021-03-22 09:27 UTC, eladdo92 commented on src/dropdown/dropdownOption.ts
> +    disabled?: boolean;
why `disabled` is on `BaseDropdownOption` and not on `TextDropdownOption`?

2021-03-22 14:49 UTC, eladdo92 approved these changes

2021-03-22 14:49 UTC, eladdo92 commented on src/dropdown/dropdown.ts
> +            const optionItemNode = this.makeListItemNode(option, enabled && !option.disabled);
I'd move the `enabled && !option.disabled` logic to line 114

2021-03-24 12:42 UTC, eifr0980 approved these changes

2021-03-24 12:42 UTC, eifr0980 commented on .eslintrc
> +    "react/react-in-jsx-scope": "off"
👑

2021-03-24 12:42 UTC, eifr0980 commented on src/dropdown/dropdown.ts
> +    constructor(parent: Element, options: DropdownOption[], props: DropdownProps) {
I still think that adding JSDocs will make be useful

2021-03-24 14:19 UTC, eladdo92 approved these changes
🚀

2021-04-01 19:53 UTC, vlad-karnauch commented on src/dropdown/dropdown.ts
> +    constructor(parent: Element, options: DropdownOption[], props: DropdownProps) {
Added these for phase 3!!!

2021-04-01 19:54 UTC, merged