feat(phase3): converted to react
vlad-karnauch/wix-onboarding pull request #4
Opened 2021-04-04 05:43 UTC by vlad-karnauch

same old dropdown assignment with a few changes

- implemented in react: see dropdown.tsx
- added tests and a test suite: run `npm run test`

2021-04-04 11:21 UTC, eladdo92 requested changes
👌

2021-04-04 11:21 UTC, eladdo92 commented on test/dropdown-driver.ts
> +        const item = optionItemsContainer?.children.item(i);
what if `optionItemsContainer` is `null`?

2021-04-04 11:21 UTC, eladdo92 commented on test/dropdown-driver.ts
> +        if (item) {
smame

2021-04-04 11:21 UTC, eladdo92 commented on test/dropdown.spec.tsx
> +function makeDriver(dropdown: JSX.Element): DropdownDriver {
rename to `renderDropdown`

2021-04-04 11:21 UTC, eladdo92 commented on test/dropdown.spec.tsx
> +        it('opens dropdown on render when true', () => {
on render -> on mount

2021-04-04 11:21 UTC, eladdo92 commented on test/dropdown.spec.tsx
> +        async function testClickWhenDisabled(params: { openByDefault: boolean }): Promise<void> {
move to the end of the file / another file

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container-driver.ts
> +            this.compareClasses(['item', 'option'], root.classList) ||
maybe add a 'text-option' class and check only it

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container-driver.ts
> +        return this.compareClasses(['item', 'divider'], root.classList) && !this.hasText(root);
checking if the class list contains `divider` is enough

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container.spec.tsx
> +        it('opens when open is true', () => {
this is the same as the first test

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container.spec.tsx
> +        it('disables when disabled is true', () => {
the same

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container.spec.tsx
> +            const option = optionsContainer.getOptionDriver(i) as OptionDriver; //"displays all options" test makes sure its not null
you use it also in 'calls onOptionClick with the right text' test

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container.spec.tsx
> +            expect(spy.lastCall.args, `option(${i}) bad text`).to.be.deep.equal([text]);
`expect(spy.lastCall.args[0], `option(${i}) bad text`).to.be.equal(text);`

2021-04-04 11:21 UTC, eladdo92 commented on test/options-container.spec.tsx
> +        function expectSpyNotCalled(spy: SinonSpy, i: number) {
move all utils to the end of the file

2021-04-04 11:21 UTC, eladdo92 commented on test/trigger.spec.tsx
> +    it('does not call onclick when disabled', () => {
combine this test with the previous one

2021-04-04 11:21 UTC, eladdo92 commented on test/util.tsx
> +import { expect } from 'chai';
delete

2021-04-04 11:35 UTC, vlad-karnauch commented on README.md
> +  const onChange = (newVal: string) => {
lol, copy-paste

2021-04-04 11:40 UTC, vlad-karnauch commented on src/app.tsx
> +    function onSelect(text: string) {
That's more declarative here

2021-04-04 12:03 UTC, vlad-karnauch commented on src/dropdown/options-container.tsx
> +                toDropdownOption(i, props, disabled ? undefined : onOptionClick)
why?

2021-04-04 12:06 UTC, vlad-karnauch commented on src/dropdown/dropdown.tsx
> +    value: string;
* @param value text to be selected before anything else is

2021-04-04 12:11 UTC, vlad-karnauch commented on test/dropdown-driver.ts
> +        const item = optionItemsContainer?.children.item(i);
Ahhhm, I think we need to talk about this, but essentially the tests assume that OptionsContainer is created with the correct component.
This shouldn't be an expect(...) because this is not part of the test, maybe I should add an exception when the driver is created?

2021-04-04 12:17 UTC, vlad-karnauch commented on test/options-container.spec.tsx
> +            expect(spy.lastCall.args, `option(${i}) bad text`).to.be.deep.equal([text]);
This also checks that there was only one parameter

2021-04-04 12:19 UTC, vlad-karnauch commented on test/util.tsx
> +import { expect } from 'chai';
lol, chai has a fail function!!! very cool.

2021-04-05 13:18 UTC, eladdo92 requested changes

2021-04-05 13:18 UTC, eladdo92 commented on src/dropdown/dropdown.tsx
> +    function handleSelect(text: string) {
add `useCallback` (why?)

2021-04-05 13:18 UTC, eladdo92 commented on src/dropdown/dropdown.tsx
> +        setOpen(!open);
https://reactjs.org/docs/faq-state.html#what-is-the-difference-between-passing-an-object-or-a-function-in-setstate

2021-04-05 13:18 UTC, eladdo92 commented on src/dropdown/options-container.tsx
> + * @param open false hide not display this component
still 😅

2021-04-05 13:18 UTC, eladdo92 commented on test/dropdown-driver.ts
> +        if (trigger) {
the `if` is needed? if it does, what happens to the test in the "else" case?

2021-04-05 13:18 UTC, eladdo92 commented on test/dropdown-selector.ts
> + * Responsible for querying the dropdown
cool 😎

2021-04-05 13:18 UTC, eladdo92 commented on test/trigger-driver.ts
> +export class TriggerDriver extends BaseSelector {
`extends BaseSelector`

2021-04-05 13:26 UTC, vlad-karnauch commented on src/dropdown/divider-option.tsx
> +export default memo(DividerOption, () => true);
lol, it was your idea, and removed

2021-04-06 10:55 UTC, vlad-karnauch commented on src/dropdown/options-container.tsx
> +            const onClick = onOptionClick ? () => onOptionClick(props.value) : undefined;
It's problematic because of the switch (divider issue again) and because of the if(open) { return null } above;

2021-04-06 11:14 UTC, eladdo92 commented on src/dropdown/options-container.tsx
> +            const onClick = onOptionClick ? () => onOptionClick(props.value) : undefined;
try:
```ts
const onClick = useCallback(() => onOptionClick?.(onOptionClick), [onOptionClick]) 
switch (props.type) { 
   case ...
```
why the `if(open)` is problematic?

2021-04-06 11:18 UTC, eladdo92 commented on src/dropdown/options-container.tsx
> +            const onClick = onOptionClick ? () => onOptionClick(props.value) : undefined;
try:
```ts
const onClick = useCallback(() => onOptionClick?.(props.value), [onOptionClick, props.value]);
switch (props.type) {
   case ...
```
why is the `if(open) { return null }` problematic?

2021-04-06 11:23 UTC, vlad-karnauch commented on src/dropdown/options-container.tsx
> +            const onClick = onOptionClick ? () => onOptionClick(props.value) : undefined;
In both cases: 

React Hook "useCallback" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?eslintreact-hooks/rules-of-hooks

2021-04-06 12:48 UTC, eladdo92 commented on src/dropdown/options-container.tsx
> +            const onClick = onOptionClick ? () => onOptionClick(props.value) : undefined;
but it's not called conditionally that the way I suggested, the `if(open)` is in another component (or am I missing something?)

2021-04-06 16:21 UTC, vlad-karnauch commented on src/dropdown/options-container.tsx
> +            const onClick = onOptionClick ? () => onOptionClick(props.value) : undefined;
added discussed updates

2021-04-08 07:35 UTC, eladdo92 approved these changes
🚀

2021-04-08 08:42 UTC, merged