Vladk/phase4
vlad-karnauch/wix-onboarding pull request #5
Opened 2021-04-11 05:49 UTC by vlad-karnauch

- Support for stylable
- broken down into component folders: `components/item`, `components/menu`, etc...

2021-04-12 07:36 UTC, eladdo92 commented on src/components/option/option.st.css
> +    cursor: pointer;
can be directly on `.root`

2021-04-12 09:38 UTC, PeterShershov requested changes

2021-04-12 09:38 UTC, PeterShershov commented on src/components/option/option.tsx
> +const Option: FC<OptionProps> = ({ text, onClick, disabled }) => {
should be named differently to avoid confusion

2021-04-12 09:38 UTC, PeterShershov commented on src/components/option/option.tsx
> +        <li className={st(classes.root, { disabled: !!disabled })} onClick={maybeOnClick}>
you can go with `disabled = false` as default in the arguments and pass `{ disabled }` to the element

2021-04-12 09:38 UTC, PeterShershov commented on src/components/option/option.tsx
> +function areEqual(a: OptionProps, b: OptionProps): boolean {
davka TextOption was better IMO

2021-04-12 09:38 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +
Why "Project"?
also extra space on line 3

2021-04-12 09:38 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +.themedDropdown Trigger {
override Trigger using psuedo-classes:
`.themedDropdown::trigger`

2021-04-12 09:38 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +    color: white;
`themedMenu::option`

2021-04-12 09:38 UTC, PeterShershov commented on test-kit/dropdown/dropdown-driver.ts
> +    clickItem(i: number): void {
`clickItemByIndex`

2021-04-12 09:38 UTC, PeterShershov commented on test-kit/menu/menu-driver.ts
> +    }
add JSDoc to all public methods, also in other drivers

2021-04-12 09:38 UTC, PeterShershov commented on test-kit/menu/menu-driver.ts
> +    private getItem(i: number) {
`...byIndex`

2021-04-12 09:38 UTC, PeterShershov commented on test/menu.spec.tsx
> +        it('opens when open', () => {
clarify this description

2021-04-12 12:04 UTC, vlad-karnauch commented on src/components/divider/divider.tsx
> +export default memo(Divider);
I feel that this version is more readable: here is a component, and let's do it memo...

2021-04-12 12:05 UTC, vlad-karnauch commented on src/components/dropdown/dropdown.tsx
> +                    className={menuClassName}
yes we can

2021-04-12 13:39 UTC, vlad-karnauch commented on src/components/item/item-props.tsx
> +export function dividerProps(): DividerProps {
to match the previous function: 
I have `optionProps(...)`, and `dividerProps()` - each returns a different kind of "item"

2021-04-12 13:59 UTC, vlad-karnauch commented on src/components/option/option.tsx
> +        <li className={st(classes.root, { disabled: !!disabled })} onClick={maybeOnClick}>
very nice

2021-04-12 14:08 UTC, vlad-karnauch commented on test-kit/menu/menu-driver.ts
> +    }
Some of the stuff has comments, but the majority is really self explanatory: 
isOpen(), isDisabled()...
That's why, as you suggested, clickItemByIndex is better than clickItem(i)

2021-04-13 10:42 UTC, PeterShershov commented on src/components/item/item-props.tsx
> +export function dividerProps(): DividerProps {
You can have both types of props providers - a function and a constant. It's creating a new instance and runs an operation for no reason.

2021-04-18 08:59 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +@st-import TextOption from './text-option/text-option.st.css';
unused

2021-04-18 08:59 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +    overflow: auto; /* scrollbar */
same comment from line 28

2021-04-18 08:59 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +    height: 1em;
should these values be in the themed stylesheet?
What is the distinction between themed and regular component stylesheet?

2021-04-18 08:59 UTC, PeterShershov commented on src/components/themed-dropdown.st.css
> +    padding-left: 0.15em;
same comment from line 28

2021-04-18 08:59 UTC, PeterShershov commented on src/components/dropdown/dropdown.tsx
> +function useToggle(openByDefault: boolean): [boolean, () => void, () => void] {
Not serious but I think that
```ts
function useToggle(openByDefault: boolean): { isOpen: boolean, close: () => void, toggle: () => void } {
```
is more readable

2021-04-18 08:59 UTC, PeterShershov commented on src/components/menu/menu.st.css
> +}
no need for that

2021-04-18 08:59 UTC, PeterShershov commented on src/components/menu/menu.st.css
> +.divider{
do you use stylable-intelligence? should prettify this with an extra space automatically

2021-04-21 14:21 UTC, eladdo92 approved these changes

2021-04-25 12:24 UTC, merged